crnk-project/crnk-framework

build.gradle
crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java
crnk-core/src/main/java/io/crnk/core/engine/internal/repository/ResponseRepositoryAdapter.java
crnk-core/src/main/java/io/crnk/core/queryspec/InMemoryEvaluator.java
crnk-core/src/main/java/io/crnk/core/resource/links/DefaultPagedLinksInformation.java
crnk-core/src/main/java/io/crnk/core/resource/meta/DefaultHasMoreResourcesMetaInformation.java
crnk-core/src/main/java/io/crnk/core/resource/meta/HasMoreResourcesMetaInformation.java
crnk-core/src/main/java/io/crnk/core/resource/meta/PagedMetaInformation.java
crnk-core/src/test/java/io/crnk/core/queryspec/InMemoryEvaluatorTest.java
crnk-core/src/test/java/io/crnk/core/resource/paging/next/HasNextBasedPagedLinksInformationTest.java
crnk-core/src/test/java/io/crnk/core/resource/paging/next/HasNextPageTestRepository.java
crnk-core/src/test/java/io/crnk/core/resource/paging/total/TotalBasedPagedLinksInformationTest.java
crnk-core/src/test/java/io/crnk/core/resource/paging/total/TotalResourceCountTestRepository.java
crnk-documentation/src/docs/asciidoc/modules.adoc
crnk-documentation/src/docs/asciidoc/repositories.adoc
crnk-jpa/src/main/java/io/crnk/jpa/JpaEntityRepository.java
crnk-jpa/src/main/java/io/crnk/jpa/JpaModule.java
crnk-jpa/src/main/java/io/crnk/jpa/JpaRelationshipRepository.java
crnk-jpa/src/main/java/io/crnk/jpa/JpaRepositoryConfig.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaRepositoryBase.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/query/AbstractQueryExecutorImpl.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/query/backend/querydsl/QuerydslExecutorImpl.java
crnk-jpa/src/main/java/io/crnk/jpa/query/JpaQueryExecutor.java
crnk-jpa/src/test/java/io/crnk/jpa/HasNextPagingEndToEndTest.java
gradle.properties

- introduced HasMoreResourcesMetaInformation
- implemented JpaModule.setTotalResourceCountUsed
- update page link computation accordingly

Support paging by providing hasNext instead of total count #14

---

crnk-meta/src/main/java/io/crnk/meta/MetaLookup.java
crnk-meta/src/main/java/io/crnk/meta/internal/JsonObjectMetaProvider.java
crnk-meta/src/main/java/io/crnk/meta/internal/ResourceMetaProviderImpl.java
crnk-meta/src/test/java/io/crnk/meta/ResourceMetaProviderTest.java
crnk-meta/src/test/java/io/crnk/meta/model/MetaPrimitiveTypeTest.java

added support in crnk-meta to map json as MetaPrimitiveType with id "base.json"

#27 support ObjectNode/JsonNode as primitive type

---

crnk-meta/src/main/java/io/crnk/meta/MetaLookup.java
crnk-meta/src/test/java/io/crnk/meta/model/MetaPrimitiveTypeTest.java

support ObjectNode/JsonNode as primitive type #27

---

crnk-client/src/main/java/io/crnk/client/http/apache/HttpClientRequest.java
crnk-client/src/main/java/io/crnk/client/http/okhttp/OkHttpRequest.java
crnk-client/src/main/java/io/crnk/client/internal/ClientStubBase.java
crnk-client/src/test/java/io/crnk/client/CharsetTest.java
crnk-client/src/test/java/io/crnk/client/HeadersTest.java
crnk-client/src/test/java/io/crnk/client/internal/ClientStubBaseTest.java
crnk-core/src/main/java/io/crnk/core/engine/http/HttpHeaders.java
crnk-core/src/main/java/io/crnk/core/engine/internal/http/JsonApiRequestProcessor.java
crnk-core/src/test/java/io/crnk/core/engine/http/JsonApiRequestProcessorTest.java
crnk-servlet/src/test/java/io/crnk/servlet/CrnkFilterTest.java
crnk-servlet/src/test/java/io/crnk/servlet/CrnkServletTest.java
crnk-servlet/src/test/java/io/crnk/servlet/ServletRequestContextTest.java

added charset information to content type for client requests and server responses

CrnkClient defaults to ISO-8859-1 instead of UTF-8 #24

---

crnk-ui/src/app/browse/browse.component.html
crnk-ui/src/app/browse/browse.component.ts
crnk-ui/src/app/browse/browse.service.ts

- type is empty after first startup and not preselect first item
- type is validated against available repositories and emptied if not available anymore
- url input component not shown in embedded mode

crnk-ui improvements #10

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java
crnk-core/src/main/java/io/crnk/core/boot/CrnkProperties.java
crnk-core/src/main/java/io/crnk/core/engine/internal/repository/ResourceRepositoryAdapter.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/test/java/io/crnk/core/engine/internal/dispatcher/controller/resource/ResourceGetTest.java
crnk-core/src/test/java/io/crnk/core/repository/ResourceRepositoryBaseTest.java

throw ResourceNotFoundException

---

crnk-core/src/main/java/io/crnk/core/queryspec/FilterSpec.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/DefaultQuerySpecDeserializerTestBase.java

add generic cast

---

crnk-brave/build.gradle
crnk-core/build.gradle
crnk-core/src/main/java/io/crnk/core/engine/internal/exception/ExceptionMapperRegistryBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/ClassUtils.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/MethodCache.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/TypeUtils.java
crnk-core/src/main/java/io/crnk/legacy/registry/DirectRepositoryEntryBuilder.java
crnk-core/src/main/java/io/crnk/legacy/repository/information/DefaultResourceRepositoryInformationBuilder.java
crnk-examples/jersey-example/build.gradle
crnk-home/build.gradle
crnk-jpa/build.gradle
crnk-meta/build.gradle
crnk-rs/build.gradle
crnk-security/build.gradle
crnk-servlet/build.gradle
crnk-validation/build.gradle

guava and apache commons removed

reduce library dependencies #55

---

crnk-brave/src/main/java/io/crnk/brave/BraveModule.java
crnk-brave/src/test/java/io/crnk/brave/BasicBraveModuleTest.java
crnk-home/src/main/java/io/crnk/home/HomeModule.java
crnk-home/src/test/java/io/crnk/home/HomeModuleTest.java
crnk-jpa/src/main/java/io/crnk/jpa/JpaModule.java
crnk-jpa/src/test/java/io/crnk/jpa/repository/JpaModuleTest.java
crnk-meta/src/main/java/io/crnk/meta/MetaModule.java
crnk-meta/src/test/java/io/crnk/meta/MetaModuleTest.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/test/java/io/crnk/operations/OperationsModuleTest.java
crnk-security/src/main/java/io/crnk/security/SecurityModule.java
crnk-security/src/test/java/io/crnk/security/SecurityModuleTest.java
crnk-test/src/main/java/io/crnk/test/mock/ClassTestUtils.java
crnk-ui/build.gradle
crnk-ui/src/main/java/io/crnk/ui/UIModule.java
crnk-ui/src/test/java/io/crnk/ui/UIModuleTest.java
crnk-validation/src/main/java/io/crnk/validation/ValidationModule.java
crnk-validation/src/test/java/io/crnk/validation/ValidationModuleTest.java

CDI in need for them to create proxies.

provide protected constructors for all modules #56

---

crnk-meta/src/main/java/io/crnk/meta/model/MetaKey.java
crnk-operations/src/test/java/io/crnk/operations/OperationsSingleEntityTest.java
crnk-operations/src/test/java/io/crnk/operations/model/VoteEntity.java
crnk-operations/src/test/resources/META-INF/persistence.xml

added test case for server-generated primar keys

more operations testing

---

crnk-test/build.gradle
crnk-test/src/main/java/io/crnk/test/mock/repository/ScheduleRepository.java
crnk-test/src/main/java/io/crnk/test/mock/repository/ScheduleRepositoryImpl.java

removed cyclic project dependency

---

crnk-client/src/main/java/io/crnk/client/CrnkClient.java
crnk-client/src/main/java/io/crnk/client/module/ClientModuleFactory.java
crnk-client/src/test/java/io/crnk/client/AbstractClientTest.java
crnk-client/src/test/java/io/crnk/client/module/ClientModuleFactoryTest.java
crnk-client/src/test/java/io/crnk/client/module/ModuleTest.java
crnk-client/src/test/java/io/crnk/client/module/TestClientModuleFactory.java
crnk-client/src/test/java/io/crnk/client/module/TestModule.java
crnk-client/src/test/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory
crnk-documentation/src/docs/asciidoc/client.adoc
crnk-documentation/src/docs/asciidoc/module_development.adoc
crnk-jpa/build.gradle
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaClientModuleFactory.java
crnk-jpa/src/main/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory
crnk-jpa/src/test/java/io/crnk/jpa/internal/JpaClientModuleFactoryTest.java
crnk-meta/build.gradle
crnk-meta/src/main/java/io/crnk/meta/internal/MetaClientModuleFactory.java
crnk-meta/src/main/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory
crnk-meta/src/test/java/io/crnk/meta/MetaClientModuleFactoryTest.java
crnk-security/build.gradle
crnk-security/src/main/java/io/crnk/security/internal/SecurityClientModuleFactory.java
crnk-security/src/main/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory
crnk-security/src/test/java/io/crnk/security/SecurityClientModuleFactoryTest.java
crnk-validation/build.gradle
crnk-validation/src/main/java/io/crnk/validation/internal/ValidationClientModuleFactory.java
crnk-validation/src/main/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory
crnk-validation/src/test/java/io/crnk/validation/internal/ValidationClientModuleFactoryTest.java

introduced ClientModuleFactory and CrnkClient.findModules using java.util.ServiceLoader.

Allow auto-discovery of client modules #73

---

crnk-cdi/src/main/java/io/crnk/cdi/internal/CdiServiceDiscovery.java
crnk-cdi/src/test/java/io/crnk/internal/boot/cdi/CdiServiceDiscoveryTest.java
crnk-documentation/src/docs/asciidoc/setup.adoc

appropriate getter/setter introduced.

Allow custom BeanManager for CdiServiceDiscovery

---

crnk-client-angular-ngrx/binding/crnk.binding.form.ts
crnk-client-angular-ngrx/binding/crnk.binding.module.ts
crnk-client-angular-ngrx/binding/crnk.binding.service.ts
crnk-client-angular-ngrx/binding/crnk.binding.utils.ts
crnk-client-angular-ngrx/operations/crnk.operations.effects.ts
crnk-client-angular-ngrx/test/crnk.operations.effects.spec.ts

update CrnkOperationsModule integration into ngrx-json-api due to (new) limited visibility of some services.

Support Angular development #90

---

crnk-client/src/main/java/io/crnk/client/CrnkClient.java
crnk-client/src/main/java/io/crnk/client/internal/ClientResourceUpsert.java
crnk-core/src/main/java/io/crnk/core/engine/information/InformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/FieldResourcePost.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourcePatch.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourcePost.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourceUpsert.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/DefaultInformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceFieldImpl.java
crnk-core/src/main/java/io/crnk/core/engine/internal/registry/DefaultRegistryEntryBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/ClassUtils.java
crnk-core/src/main/java/io/crnk/core/engine/registry/RegistryEntry.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/main/java/io/crnk/core/module/internal/DefaultRepositoryInformationProviderContext.java
crnk-meta/src/main/java/io/crnk/meta/MetaModule.java

- CrnkClient ignores missing relationships upon GET
- CrnkClient.getRepositoryForType(A, B) works without A having relationship to B

relationship improvements

---

crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceInformation.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourceUpsert.java
crnk-core/src/main/java/io/crnk/core/engine/parser/TypeParser.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceFieldInformationProvider.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceInformationProvider.java
crnk-jpa/src/test/java/io/crnk/jpa/information/JpaResourceInformationProviderTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/AttributeNamingEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/BasicAttributesEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/HasNextPagingEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/JpaQueryParamsEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/JpaQuerySpecEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/OptimisticLockingEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/integration/SaveRelationshipWithResourceEndToEndTest.java
crnk-jpa/src/test/java/io/crnk/jpa/model/ManyToManyOppositeEntity.java
crnk-jpa/src/test/java/io/crnk/jpa/model/ManyToManyTestEntity.java
crnk-jpa/src/test/java/io/crnk/jpa/model/OneToOneTestEntity.java
crnk-jpa/src/test/java/io/crnk/jpa/query/AbstractJpaTest.java
crnk-jpa/src/test/resources/META-INF/persistence.xml
crnk-rs/src/main/java/io/crnk/rs/CrnkFeature.java
gradle.properties

fixed information builder for one-to-one and added further test cases

crnk-jpa one-to-one relationship fix

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java
crnk-core/src/main/java/io/crnk/core/boot/CrnkProperties.java
crnk-spring/src/main/java/io/crnk/spring/boot/CrnkSpringBootProperties.java
crnk-spring/src/main/java/io/crnk/spring/boot/v3/CrnkConfigV3.java
crnk-spring/src/test/java/io/crnk/spring/boot/CrnkConfigV3Test.java

- Spring Boot - add support to allow unknown parameters

---

crnk-core/src/main/java/io/crnk/core/queryspec/InMemoryEvaluator.java
crnk-core/src/test/java/io/crnk/core/queryspec/InMemoryEvaluatorTest.java

should not allow to move past list size and return a bad request error.

check page offset in QuerySpec.apply(...)

---

crnk-client-angular-ngrx/README.md
crnk-client-angular-ngrx/meta/meta.element.ts
crnk-client-angular-ngrx/src/gen/java/io/crnk/client/ngrx/gen/GeneratorExecutor.java
crnk-core/src/main/java/io/crnk/core/engine/registry/ResourceRegistry.java
crnk-gen-typescript/build.gradle
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/GeneratorTrigger.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/RuntimeClassLoaderFactory.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/cdi/CdiMetaResolver.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/cdi/CdiRunner.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/deltaspike/DeltaspikeRunner.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/ForkedGenerateTypescriptTask.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/ForkedGeneratorMain.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/GenerateTypescriptTask.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorConfig.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorExtension.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorPlugin.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSNpmConfiguration.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/internal/TSGenerator.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/internal/TSGeneratorRuntimeContext.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/internal/TSGeneratorRuntimeContextImpl.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/model/libraries/NgrxJsonApiLibrary.java
crnk-gen-typescript/src/test/java/io/crnk/gen/typescript/GenerateTypescriptTaskTest.java
crnk-gen-typescript/src/test/resources/expected_schedule_with_expressions.ts
crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts

- forking of processes
- cdi support
- updated npm dependencies

Typescript gen updates

---

crnk-activiti/src/test/java/io/crnk/activiti/example/approval/ApprovalRelationshipRepository.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceFieldAccess.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceFieldInformationProvider.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceFieldInformationProviderBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/ResourceMapper.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/DefaultInformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/DefaultResourceFieldInformationProvider.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceFieldImpl.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/jackson/JacksonResourceFieldInformationProvider.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiField.java
crnk-core/src/test/java/io/crnk/core/engine/ResourceFieldAccessTest.java
crnk-core/src/test/java/io/crnk/core/engine/internal/information/DefaultInformationBuilderTest.java
crnk-core/src/test/java/io/crnk/core/mock/models/Task.java
crnk-core/src/test/java/io/crnk/core/queryspec/AbstractQuerySpecTest.java
crnk-core/src/test/java/io/crnk/core/resource/DefaultResourceInformationProviderTest.java
crnk-core/src/test/java/io/crnk/core/resource/internal/DocumentMapperTest.java
crnk-documentation/src/docs/asciidoc/resource.adoc
crnk-jpa/src/test/java/io/crnk/jpa/mapping/CustomResourceFieldTest.java
crnk-meta/src/main/java/io/crnk/meta/internal/resource/ResourceMetaParitition.java
crnk-meta/src/main/java/io/crnk/meta/model/MetaAttribute.java
crnk-ui/package-lock.json

Introduced readable aka WRITE_ONLY jackson annotation support

---

crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java
crnk-core/src/main/java/io/crnk/core/engine/registry/ResourceRegistry.java
crnk-core/src/test/java/io/crnk/core/resource/registry/ResourceRegistryTest.java

@remmeier Don't know whether it's a provate case or  more generic.. But in my case it would be nice to have them

Added methods

---

crnk-security/src/main/java/io/crnk/security/SecurityConfig.java
crnk-security/src/test/java/io/crnk/security/SecurityConfigTest.java

1. Added chaining support
2. Added multiple resource-permission definitions

Improved security module config

---

crnk-activiti/src/main/java/io/crnk/activiti/mapper/ActivitiResourceMapper.java
crnk-core/src/main/java/io/crnk/core/engine/http/HttpHeaders.java
crnk-core/src/main/java/io/crnk/core/engine/information/bean/BeanAttributeInformation.java
crnk-core/src/main/java/io/crnk/core/engine/information/bean/BeanInformation.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/DocumentMapper.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/DocumentMapperUtil.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/ResourceMapper.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/jackson/LinksInformationSerializer.java
crnk-core/src/main/java/io/crnk/core/engine/query/QueryAdapter.java
crnk-core/src/main/java/io/crnk/core/queryspec/internal/QuerySpecAdapter.java
crnk-core/src/main/java/io/crnk/core/queryspec/internal/QuerySpecAdapterBuilder.java
crnk-core/src/main/java/io/crnk/legacy/internal/QueryParamsAdapter.java
crnk-core/src/test/java/io/crnk/core/engine/http/JsonApiRequestProcessorTest.java
crnk-core/src/test/java/io/crnk/core/engine/internal/jackson/JacksonResourceFieldInformationProviderNamingTest.java
crnk-core/src/test/java/io/crnk/core/engine/internal/jackson/LinksInformationSerializerTest.java
crnk-core/src/test/java/io/crnk/core/mock/models/TaskLinks.java
crnk-core/src/test/java/io/crnk/core/resource/internal/DocumentMapperTest.java
crnk-core/src/test/java/io/crnk/core/resource/internal/ObjectLinkDocumentMapperTest.java
crnk-documentation/src/docs/asciidoc/repositories.adoc
crnk-test/src/main/java/io/crnk/test/mock/models/Task.java

new Crnk-Compact header introduced to skip self/related link oomputation while maintaining JSON API compatibility by default.

support compact responses #179

---

crnk-core/src/main/java/io/crnk/core/engine/internal/http/HttpRequestContextBaseAdapter.java
crnk-core/src/main/java/io/crnk/core/queryspec/DefaultQuerySpecDeserializer.java
crnk-core/src/main/java/io/crnk/core/queryspec/InMemoryEvaluator.java
crnk-core/src/test/java/io/crnk/core/engine/http/HttpRequestContextBaseAdapterTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/InMemoryEvaluatorTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/DefaultQuerySpecDeserializerTestBase.java
crnk-operations/src/main/java/io/crnk/operations/client/OperationsCall.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsRequestProcessor.java
crnk-spring/src/main/java/io/crnk/spring/boot/autoconfigure/CrnkUIAutoConfiguration.java
crnk-spring/src/main/resources/META-INF/spring.factories
crnk-spring/src/test/java/io/crnk/spring/boot/BasicSpringBootTest.java

registered auto configuration of ui module

When the app starts, accessing "/browse" does not work #2

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/ControllerRegistryBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/DocumentMapper.java

adds the ability to swap out classes more easily

enhance customizability

---

crnk-documentation/src/docs/asciidoc/generation.adoc
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/spring/SpringRunner.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/spring/SpringRuntimeConfig.java
gradle.properties

- clearer structuring of docs
- defaultProperties for spring runtime
- initializerMethod for spring runtime

typescript-gen: documentation and spring refinements #168

---

crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/IncludeLookupUtil.java
crnk-core/src/main/java/io/crnk/core/engine/internal/repository/RepositoryRequestSpecImpl.java
crnk-core/src/main/java/io/crnk/core/queryspec/DefaultQuerySpecDeserializer.java
crnk-core/src/main/java/io/crnk/core/queryspec/QuerySpec.java
crnk-core/src/main/java/io/crnk/core/repository/RelationshipRepositoryBase.java
crnk-core/src/main/java/io/crnk/core/repository/implicit/ImplicitOwnerBasedRelationshipRepository.java
crnk-core/src/test/java/io/crnk/core/engine/internal/repository/ImplicitOwnerBasedRelationshipRepositoryTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/QuerySpecTest.java

engine should access QuerySpec with both resourceType and resourceClass to let user choose what to use.

hardening of QuerySpec #197

---

crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsRequestProcessor.java

New method OperationsModule.apply(...) introduced.

Allow programmatic access to operations API #220

---

crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-core/src/test/java/io/crnk/core/resource/DefaultResourceInformationProviderTest.java

Added more checks for supporting custom get-named methods

---

crnk-client/src/main/java/io/crnk/client/internal/ClientStubBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/JsonApiUrlBuilder.java
crnk-core/src/main/java/io/crnk/core/queryspec/DefaultQuerySpecSerializer.java

Exposing `QuerySpecSerializer` in `crnk-client` ref. #266

crnk-client QuerySpecSerializer exposure

---

crnk-client/src/main/java/io/crnk/client/CrnkClient.java
crnk-core/src/main/java/io/crnk/core/engine/information/InformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceInformation.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceInformationProvider.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/DefaultInformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/DefaultResourceInformationProvider.java
crnk-core/src/main/java/io/crnk/core/engine/internal/registry/DefaultRegistryEntryBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiResource.java
crnk-core/src/test/java/io/crnk/core/engine/internal/information/DefaultInformationBuilderTest.java
crnk-core/src/test/java/io/crnk/core/module/ModuleRegistryTest.java
crnk-core/src/test/java/io/crnk/core/module/TestResourceInformationProvider.java
crnk-core/src/test/java/io/crnk/core/resource/DefaultResourceInformationProviderTest.java
crnk-core/src/test/java/io/crnk/core/resource/ResourceInformationTest.java
crnk-core/src/test/java/io/crnk/core/resource/registry/RegistryEntryTest.java
crnk-core/src/test/java/io/crnk/core/resource/registry/ResourceRegistryTest.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceInformationProvider.java

To replace the previous Pull Request for issue #263

Issue #263 resolution: merge conflict resolved

---

crnk-client/src/main/java/io/crnk/client/internal/ClientStubBase.java
crnk-client/src/test/java/io/crnk/client/suite/ClientTestContainer.java
crnk-core/src/main/java/io/crnk/core/engine/document/ResourceIdentifier.java
crnk-core/src/main/java/io/crnk/core/engine/http/HttpResponse.java
crnk-core/src/main/java/io/crnk/core/engine/internal/http/JsonApiRequestProcessorBase.java
crnk-core/src/main/java/io/crnk/core/repository/response/JsonApiResponse.java
crnk-reactive/src/test/java/io/crnk/reactive/NonReactiveWithWorkerTest.java
crnk-servlet/src/test/java/io/crnk/servlet/reactive/ReactiveStressTest.java
crnk-servlet/src/test/java/io/crnk/servlet/resource/ReactiveServletTestContainer.java
crnk-test/src/main/java/io/crnk/test/suite/RelationIdAccessTestBase.java
crnk-test/src/main/java/io/crnk/test/suite/TestContainer.java

- 204 status code does not serialize result document
- logging improvements
- test refinements

refinement of reactive setup #198

---

crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/spring/SpringRunner.java

SpringApplication class of Spring Boot broke the constructor contract from Object[] to Class[].

Spring Boot 2 support for Typescript generation #297

---

crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/DefaultResourceInformationProvider.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/main/java/io/crnk/core/module/SimpleModule.java
crnk-core/src/main/java/io/crnk/core/queryspec/pagingspec/VoidPagingBehavior.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiResource.java
crnk-core/src/test/java/io/crnk/core/engine/internal/document/mapper/AbstractDocumentMapperTest.java
crnk-core/src/test/java/io/crnk/core/module/SimpleModuleTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/AbstractQuerySpecTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/DefaultQuerySpecSerializerTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/pagingspec/VoidPagingBehaviorTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/EnforcedDotPathSeparatorQuerySpecDeserializerTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/LegacyQuerySpecDeserializerTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/QuerySpecRepositoryTest.java

Allow a custom paging behavior to become app default #284

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkProperties.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/IncludeLookupUtil.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-core/src/test/java/io/crnk/core/engine/internal/document/mapper/lookup/IncludeLookupUtilTest.java
crnk-documentation/src/docs/asciidoc/setup.adoc
crnk-documentation/src/docs/releases/latest/info.html

crnk.config.lookup.behavior.default

property to specify default lookup behavior #323

---

crnk-core/src/main/java/io/crnk/core/exception/ForbiddenException.java

Fix "Forbidden" typo

---

crnk-core/src/main/java/io/crnk/core/repository/foward/strategy/GetFromOwnerStrategy.java
crnk-core/src/test/java/io/crnk/core/repository/forward/OwnerFowardingRelationshipRepositoryTest.java

fixed the parametr queryspec bug

Fix queryspec bug in GetFromOwnerStrategy class

---

crnk-core/src/main/java/io/crnk/core/engine/internal/repository/RepositoryAdapterUtils.java
crnk-core/src/main/java/io/crnk/core/queryspec/mapper/DefaultQuerySpecUrlMapper.java
crnk-core/src/test/java/io/crnk/core/mock/models/CustomPagingPojo.java
crnk-core/src/test/java/io/crnk/core/mock/models/Task.java
crnk-core/src/test/java/io/crnk/core/mock/repository/CustomPagingPojoRepository.java
crnk-core/src/test/java/io/crnk/core/queryspec/mapper/DefaultQuerySpecUrlMapperSerializerTest.java

Improved logics to retrieve the appropriate PagingSpec from request, based on currently handled ResourceEntry
Fixed #453

Multiple paging specs behaviours by complex requests

---

crnk-core/build.gradle
versions.properties

Ripple effect of jhalterman/typetools#48

Update TypeTools to 0.6.1 for upstream bugfix

---

crnk-client/src/main/java/io/crnk/client/CrnkClient.java
crnk-client/src/test/java/io/crnk/client/AbstractClientTest.java
crnk-client/src/test/java/io/crnk/client/inheritance/SamePathInheritanceClientTest.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/RepositoryData.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/cyclic/CyclicResourceARepository.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/cyclic/CyclicResourceBRespository.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/cyclic/CyclicResourceCRepository.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/related/RelatedResourceARepository.java
crnk-client/src/test/java/io/crnk/client/inheritance/repositories/related/RelatedResourceBRepository.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/cyclic/CyclicResourceA.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/cyclic/CyclicResourceASub1.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/cyclic/CyclicResourceB.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/cyclic/CyclicResourceC.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/related/RelatedResourceA.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/related/RelatedResourceAsub1.java
crnk-client/src/test/java/io/crnk/client/inheritance/resources/related/RelatedResourceB.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/path/PathBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/registry/RegistryEntry.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiRelation.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiRelationId.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceInformationProvider.java

- lookup relationship fields on subtypes for incoming requests if not found on root type
- properly setup parent/child relationship in crnk-client

fix for inheritance with a single repository per type hierarchy #480

---

build.gradle

Fixed a typo in the project's URL and also switch to HTTPS protocol

Fixed typo in project URL

---

crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java
crnk-core/src/test/java/io/crnk/core/engine/internal/resource/NestedResourceTest.java

I think it is actually enough (at least for singular nesting) to recursivley call getResourceUrl on the parent to compute the correct url.
I am missing something?

Nesting for multiple levels

---

crnk-core/src/main/java/io/crnk/core/repository/ReadOnlyRelationshipRepositoryBase.java
crnk-core/src/main/java/io/crnk/core/repository/ReadOnlyResourceRepositoryBase.java
crnk-core/src/main/java/io/crnk/core/repository/ResourceRepositoryBase.java
crnk-core/src/test/java/io/crnk/core/engine/repository/ResourceRepositoryBaseTest.java
crnk-core/src/test/java/io/crnk/core/repository/ReadOnlyRelationshipRepositoryBaseTest.java
crnk-core/src/test/java/io/crnk/core/repository/ReadOnlyResourceRepositoryBaseTest.java
crnk-documentation/src/docs/releases/latest/info.html

return HTTP 405 in read-only repos

---

crnk-meta/src/main/java/io/crnk/meta/provider/MetaPartitionBase.java

This is the analogue of #512 for Crnk 3.x

Recursive allocateMetaElement only for known Collections

---

crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java
crnk-core/src/main/java/io/crnk/core/engine/registry/ResourceRegistry.java
crnk-core/src/test/java/io/crnk/core/engine/internal/resource/NestedResourceTest.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java

- getResourceUrl() now supportes multi-level nested resources
- added a getResourcePath() in case the caller doesn't want the full URL
- added support to OperationsModule for nested resources

Multi-Level Nested Resources (2nd Try)

---

build.gradle
crnk-integration-examples/spring-boot-minimal-example/build.gradle

Fixed gradle build problems with running the example projects under crnk-integration-example.

Fixed problems with crnk-integration-examples builds

---

crnk-client/src/main/java/io/crnk/client/internal/ClientStubBase.java
crnk-client/src/main/java/io/crnk/client/internal/ResourceRepositoryStubImpl.java
crnk-client/src/test/java/io/crnk/client/BulkClientTest.java
crnk-core/src/main/java/io/crnk/core/engine/information/repository/ResourceRepositoryInformation.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/BaseController.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourceDeleteController.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourceUpsert.java
crnk-core/src/main/java/io/crnk/core/engine/internal/repository/ResourceRepositoryAdapterImpl.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/test/java/io/crnk/operations/OperationsDeleteTest.java

Closes: https://github.com/crnk-project/crnk-framework/issues/639

Add Support for Bulk Delete

---

crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/OASUtils.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/NestedDelete.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/NestedGet.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/NestedPatch.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/NestedPost.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/RelationshipDelete.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/RelationshipGet.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/RelationshipPatch.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/operations/RelationshipPost.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/NestedDeleteTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/NestedGetTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/NestedOperationsBaseTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/NestedPatchTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/NestedPostTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/RelationshipDeleteTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/RelationshipGetTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/RelationshipPatchTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/operations/RelationshipPostTest.java
crnk-gen/crnk-gen-openapi/src/test/resources/gold/complex.yaml

Correct relationship and related resource paths

---

crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/path/PathBuilder.java

Infinite Loop in PathBuilder.findSelfOrSubtypeByField removed

---

crnk-core/src/main/java/io/crnk/core/engine/document/Resource.java
crnk-core/src/test/java/io/crnk/core/engine/internal/document/mapper/DocumentMapperTest.java

https://github.com/crnk-project/crnk-framework/issues/715

Order of attributes are not honored

---

crnk-core/src/main/java/io/crnk/core/queryspec/FilterOperator.java
crnk-core/src/test/java/io/crnk/core/queryspec/InMemoryEvaluatorTestBase.java

[issue 730](https://github.com/crnk-project/crnk-framework/issues/730)

[issue-730] fixed NEQ filter for multiple values

---

.editorconfig
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/OASResource.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PatchResource.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PostResource.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PostResourceData.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PostResources.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PatchResourceTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PostResourceDataTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PostResourceTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PostResourcesTest.java
crnk-gen/crnk-gen-openapi/src/test/resources/gold/complex.yaml
crnk-gen/crnk-gen-openapi/src/test/resources/gold/simple.yaml

Fixes https://github.com/crnk-project/crnk-framework/issues/724

Generate OpenAPI with 'data' top-level element in POST/PATCH operations

---

crnk-core/src/main/java/io/crnk/core/engine/internal/jackson/LinksInformationSerializer.java
crnk-core/src/test/java/io/crnk/core/engine/internal/jackson/LinksInformationSerializerTest.java

fix: respect JsonProperty annotation while generating links

---

build.gradle
crnk-bom/build.gradle
crnk-documentation/src/docs/asciidoc/setup.adoc
crnk-gen/crnk-gen-gradle/src/main/java/io/crnk/gen/gradle/task/InMemoryGeneratorTask.java
crnk-integration-examples/spring-boot-example/src/test/java/io/crnk/example/springboot/simple/SpringBootSimpleExampleApplicationTests.java
crnk-setup/crnk-setup-spring-boot1/src/test/java/io/crnk/spring/boot/BasicSpringBoot1Test.java
crnk-setup/crnk-setup-spring-boot2/src/test/java/io/crnk/spring/boot/BasicSpringBoot2Test.java
crnk-ui/build.gradle
crnk-ui/src/test/java/io/crnk/ui/UIModuleTest.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- Gradle update to use new publish plugins
- Disabled UI frontend as not maintained, presentation model remains.
- Updated publishing
Pending: publishing to GitHub packages & GitHub actions integration

Move to maven central #802

---

crnk-client/src/test/java/io/crnk/client/action/JsonApiActionResponseTest.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/ResourceMapper.java
crnk-test/src/main/java/io/crnk/test/mock/models/Schedule.java

* Added JsonInclude Test
* Fixed JsonInclude.Non_Empty
* isDefaultNodeValue method fix

Fix JsonInclude NON_EMPTY on collection
