crnk-project/crnk-framework

crnk-core/src/main/java/io/crnk/core/queryspec/DefaultQuerySpecDeserializer.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/DefaultQuerySpecDeserializerTestBase.java

fix #1
If an unknown Parameter is passed, `deserializeUnknown` will be called so you can easily intercept it.
By default it will throw `IllegalStateException` as before.

add deserializeUnknown method

---

crnk-brave/src/test/java/io/crnk/brave/AbstractBraveModuleTest.java
crnk-client/src/test/java/io/crnk/client/AbstractClientTest.java
crnk-examples/jersey-example/src/test/java/io/crnk/example/jersey/JerseyApplicationTest.java
crnk-jpa/build.gradle
crnk-jpa/src/main/java/io/crnk/jpa/internal/query/AnyUtils.java
crnk-jpa/src/main/java/io/crnk/jpa/meta/internal/AbstractEntityMetaProvider.java
crnk-jpa/src/main/java/io/crnk/jpa/meta/internal/AbstractJpaDataObjectProvider.java
crnk-jpa/src/main/java/io/crnk/jpa/meta/internal/EmbeddableMetaProvider.java
crnk-jpa/src/test/java/io/crnk/jpa/AbstractJpaJerseyTest.java
crnk-meta/src/main/java/io/crnk/meta/MetaLookup.java
crnk-meta/src/main/java/io/crnk/meta/internal/JsonObjectMetaProvider.java
crnk-meta/src/main/java/io/crnk/meta/internal/MetaDataObjectProvider.java
crnk-meta/src/main/java/io/crnk/meta/internal/ResourceMetaProviderImpl.java
crnk-meta/src/test/java/io/crnk/meta/AbstractMetaJerseyTest.java
crnk-operations/src/test/java/io/crnk/operations/AbstractOperationsTest.java
crnk-rs/src/test/java/io/crnk/rs/InteroperabilityTest.java
crnk-rs/src/test/java/io/crnk/rs/UriInfoServiceUrlProviderTest.java
crnk-rs/src/test/java/io/crnk/rs/controller/ControllerTest.java
crnk-security/src/test/java/io/crnk/security/SecurityModuleIntTest.java
crnk-test/src/main/java/io/crnk/test/JerseyTestBase.java
crnk-ui/build.gradle
crnk-validation/build.gradle
crnk-validation/src/test/java/io/crnk/validation/AbstractValidationTest.java
gradle.properties

- random port for Jersey tests
- proper npm/resource task dependencies in crnk-ui
- enabled parallel build
- crnk-validation and crnk-jpa makes partial use of crnk-test
- fixed random build failure in meta lookup due to duplicate list issues

build improvements

---

crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/RuntimeClassLoaderFactory.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorPlugin.java
crnk-gen-typescript/src/main/resources/logback-test.xml

- added application jars as task input for generateTypescript for proper up-to-date checking
- logback-test.xml to suppress non-error logging during typescript generation

Support Typescript generation #12

---

crnk-gen-typescript/build.gradle
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/RuntimeClassLoaderFactory.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/deltaspike/DeltaspikeRunner.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/GenerateTypescriptTask.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorPlugin.java

- update-to-date check improvements
- disposal of deltaspike container after typescript generator, can lead to classpath issues otherwise due to use of gradle wrapper and repeated invocations (like beans.xml not found)

Support Typescript generation refinement #12

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkProperties.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/IncludeLookupSetter.java
crnk-core/src/test/java/io/crnk/core/mock/models/HierarchicalTask.java
crnk-core/src/test/java/io/crnk/core/mock/repository/HierarchicalTaskRelationshipRepository.java
crnk-core/src/test/java/io/crnk/core/resource/internal/IncludeLookupSetterBaseTest.java

introduced flag to enable/disable pagination on included resources. In most use cases not necessary but cyclic dependencies could leading back to the main resources could be paged as well, which is highly undesirable. So flag is disabled by default.

ambiguous pagination #50

---

crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/RuntimeClassLoaderFactory.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/model/TSElementBase.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/model/TSObjectType.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/processor/TSExpressionObjectProcessor.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/transform/TSMetaDataObjectTransformation.java
crnk-gen-typescript/src/test/resources/expected_schedule_with_expressions.ts

- generated expression classes lazily initialize relationships to avoid cycles in initialization
- meta id added to expression classes
- default logback-test.xml provided with non provided by application
- inheritance support for expression classes by included inherited fields

Typescript generation refinement #12

---

crnk-core/src/main/java/io/crnk/core/engine/document/Resource.java
crnk-core/src/main/java/io/crnk/core/engine/document/ResourceIdentifier.java
crnk-core/src/test/java/io/crnk/core/resource/ResourceEqualsContractTest.java

fix for Resource.equals ignoring id and type inherited from ResourceIdentifier.

Resource.equals fix

---

crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/FieldResourceGet.java

fix #49 
Checklist:
The problem with the response beeing `{}` seems to be the value `present`.
```Java
public class Document implements MetaContainer, LinksContainer {
@JsonInclude(Include.NON_EMPTY)
@JsonDeserialize(using = DocumentDataDeserializer.class)
@JsonSerialize(using = NullableSerializer.class)
private Nullable<Object> data = Nullable.empty();
//...
```
data.preset is by default false.
```Java
private void setResponse(HttpRequestContext requestContext, Response crnkResponse)
throws IOException {
if (crnkResponse != null) {
ObjectMapper objectMapper = moduleContext.getObjectMapper();
String responseBody = objectMapper.writeValueAsString(crnkResponse.getDocument());
requestContext.setResponse(crnkResponse.getHttpStatus(), responseBody); …
```

set preset for null values

---

crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/path/PathBuilder.java
crnk-core/src/test/java/io/crnk/core/engine/internal/dispatcher/path/PathBuilderTest.java

updated PathBuilder to return null to signal no match as in all the other cases.

Crnk throws a ResourceException when requesting "/" #61

---

crnk-cdi/src/main/java/io/crnk/cdi/internal/CdiServiceDiscovery.java
crnk-cdi/src/test/java/io/crnk/internal/boot/cdi/CdiServiceDiscoveryTest.java
crnk-cdi/src/test/java/io/crnk/internal/boot/cdi/model/CdiTestExceptionMapper.java
crnk-core/src/main/java/io/crnk/core/engine/internal/exception/ExceptionMapperRegistryBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/exception/ExceptionMapperType.java

adjusted implementation accordingly to make use of TypeLiteral to search for generic instead of raw type.

Support ExceptionMapper lookup with CDI #64

---

crnk-jpa/src/main/java/io/crnk/jpa/JpaModule.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/QueryFactoryDiscovery.java
crnk-jpa/src/test/java/io/crnk/jpa/internal/QueryFactoryDiscoveryTest.java

makes use of QueryDSL if available on classpath

JpaModule: auto discovery of QueryDSL vs Criteria backend #74

---

crnk-core/src/main/java/io/crnk/core/engine/information/contributor/ResourceFieldContributor.java
crnk-core/src/main/java/io/crnk/core/engine/information/contributor/ResourceFieldContributorContext.java
crnk-core/src/main/java/io/crnk/core/engine/information/resource/ResourceInformation.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/test/java/io/crnk/core/engine/information/contributor/ResourceFieldContributorTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/repository/TaskToProjectRelationshipRepository.java

ResourceFieldContributor introduced that allows to introduce new fields on a resource without modifying the resources or having to implement an entire ResourceInformation builder. Provides an easy way
to attach new relationships to existing code base.

ResourceFieldContributor for relationship repositories

---

crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/IncludeLookupSetter.java
crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/IncludeLookupUtil.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/DefaultInformationBuilder.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/DefaultResourceInformationProvider.java
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/jackson/JacksonModule.java
crnk-core/src/main/java/io/crnk/core/module/Module.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/JsonApiRelation.java
crnk-core/src/main/java/io/crnk/core/resource/annotations/LookupIncludeBehavior.java
crnk-core/src/test/java/io/crnk/core/module/SimpleModuleTest.java
crnk-core/src/test/java/io/crnk/core/queryspec/AbstractQuerySpecTest.java
crnk-core/src/test/java/io/crnk/core/resource/DefaultResourceInformationProviderTest.java
crnk-core/src/test/java/io/crnk/core/resource/internal/IncludeLookupUtilTest.java
crnk-core/src/test/java/io/crnk/legacy/queryParams/AbstractQueryParamsTest.java
crnk-core/src/test/java/io/crnk/legacy/queryParams/QueryParamsAdapterTest.java
crnk-jpa/src/main/java/io/crnk/jpa/JpaModule.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceInformationProvider.java
crnk-jpa/src/test/java/io/crnk/jpa/JpaPartialEntityExposureTest.java
crnk-jpa/src/test/java/io/crnk/jpa/JpaResourceInformationProviderTest.java
crnk-jpa/src/test/java/io/crnk/jpa/mapping/CustomResourceFieldTest.java
crnk-meta/src/main/java/io/crnk/meta/MetaModule.java
crnk-rs/src/test/java/io/crnk/rs/JaxrsModuleTest.java

As discussed via Gitter, this PR changes the handling of the lookup behavior so that relationship annotations can override the default global setting.  It introduces a new DEFAULT for lookup behavior and makes that the actual default if no other value is specified by the relationship annotation.  When the relationship lookup behavior is set to DEFAULT, it will look to the globally set value.  If the relationship lookup behavior is set to DEFAULT and the globally value is unset, the default will be up to the resource information provider in use (NONE, usually... although JPA does something different).  If the relationship lookup behavior is set to something other than DEFAULT, then that value will be used no matter what the value of the global behavior.

Relationship repository lookup behavior overrides the global setting

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java

This PR changes the ordering of CrnkBoot bootstrapping to move setting of the PropertiesProvider on to the ModuleRegistry much earlier in the boot process.  With my last PR, I added the ability to retrieve the PropertiesProvider from within the ModuleContext where it could be used as necessary.  However, I didn't realize that the PropertiesProvider was not being set on the ModuleRegistry until the end of bootstrap.  This change allows for Module implementations to get the correct PropertiesProvider instance while they are in the midst of bootstrapping and fixes our use case of this functionality.

Set the PropertiesProvider on to the ModuleRegistry at the beginning of boot

---

crnk-client-angular-ngrx/binding/crnk.binding.form.ts
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/TSGeneratorExtension.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/internal/TSGenerator.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/processor/TSImportProcessor.java
crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/transform/TSMetaPrimitiveTypeTransformation.java

current store contents now gets compared with form value changes to avoid uncessary patch actions.

Angular: avoid unncessary patchResource actions in FormBinding #121

---

crnk-client-angular-ngrx/binding/crnk.binding.form.ts
crnk-client-angular-ngrx/test/crnk.binding.form.spec.ts
crnk-client-angular-ngrx/test/crnk.test.editor.component.html
crnk-documentation/src/docs/asciidoc/angular.adoc

introduced dirty and valid observables to get current status of a FormBinding. The observables aggregate store and form information to determine the current status.

dirty and valid status for Angular FormBinding

---

crnk-client-angular-ngrx/binding/crnk.binding.service.ts
crnk-client-angular-ngrx/binding/crnk.binding.table.ts

table binding makes use of proper zone to search for latest query

ngrx-json-api zone fix @crnk/angular-ngrx

---

crnk-core/src/main/java/io/crnk/core/boot/CrnkProperties.java
crnk-core/src/main/java/io/crnk/core/engine/internal/http/JsonApiRequestProcessor.java
crnk-core/src/test/java/io/crnk/core/engine/http/JsonApiRequestProcessorTest.java
crnk-servlet/src/main/java/io/crnk/servlet/CrnkServlet.java
crnk-servlet/src/test/java/io/crnk/servlet/CrnkServletRejectJsonTest.java
crnk-servlet/src/test/java/io/crnk/servlet/CrnkServletTest.java

Adapt the JsonApiRequestProcessor and the CrnkServlet to accept HTTP
requests with 'Accept: application/json' (instead of
'application/vnd.api+json') too. This makes it easier to integrate with
tools that are not aware of JSON-API specifically.
To revert to the old behaviour, enable the configuration property
'crnk.config.resource.request.rejectPlainJson'.
Motivation: Yes, the JSON-API standard mandates that both client and server use the `application/vnd.api+json` Accept/Content-Type headers. But for GET requests, we think it is fine to send back 'application/vnd.api+json' even when the client has requested 'application/json'. This makes working with tools/frontend that are not aware of JSON API specifically easier (generic REST client libraries; REST testing tools, etc.) Sure, all of …

Handle 'Accept: application/json' messages as JSON-API requests by default

---

crnk-spring/src/main/java/io/crnk/spring/boot/autoconfigure/CrnkErrorControllerAutoConfiguration.java

ignoring AutoConfiguration that does not exist in SpringBoot 2.x. Still needs to be properly implemented for the 2.x version.

spring boot 2.x ErrorMvc workaround #195

---

crnk-client-angular-ngrx/binding/crnk.binding.table.js
crnk-client-angular-ngrx/binding/crnk.binding.table.ts
crnk-client-angular-ngrx/binding/crnk.binding.utils.ts
crnk-client-angular-ngrx/expression/crnk.expression.ts
crnk-client-angular-ngrx/meta/meta.element.ts
crnk-client-angular-ngrx/test/crnk.binding.form.spec.ts
crnk-client-angular-ngrx/test/crnk.binding.table.spec.ts
crnk-client-angular-ngrx/test/crnk.expression.spec.ts
crnk-client-angular-ngrx/test/crnk.test.editor.component.html
crnk-client-angular-ngrx/test/crnk.test.table.component.html
crnk-client-angular-ngrx/test/crnk.test.table.component.ts
crnk-documentation/src/docs/asciidoc/angular.adoc

- update documentation
- allow to support tables other than primeng
- allow to add custom QueryParameters to the table binding (next to the one provided by the table)
- allow quick access to sort/filter parameter naming from expressions

Angular binding improvements #252

---

crnk-jpa/src/main/java/io/crnk/jpa/annotations/JpaResource.java
crnk-jpa/src/main/java/io/crnk/jpa/internal/JpaResourceInformationProvider.java
crnk-jpa/src/test/java/io/crnk/jpa/information/JpaResourceInformationProviderTest.java
crnk-jpa/src/test/java/io/crnk/jpa/model/JpaResourcePathTestEntity.java

Allow setting resource path for JPA entity through @JpaResource annotation on JPA entity.
Old behavior of JPA module not changed.

Allow setting resource path for JPA entity through @JpaResource 

---

crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java

Fixed an issue by checking that a field has the JsonApiRelationId annotation before setting it as an id to a relationship field.
Refer to https://github.com/crnk-project/crnk-framework/issues/378 for more details.

Attribute treated as a JsonApiRelationId even though not annotated

---

crnk-core/src/main/java/io/crnk/core/engine/internal/registry/RegistryEntryImpl.java
crnk-core/src/main/java/io/crnk/core/module/ModuleRegistry.java
crnk-core/src/test/java/io/crnk/core/engine/internal/resource/InheritanceWithoutSubtypeRepositoryTest.java
crnk-gen-typescript/src/main/java/io/crnk/gen/runtime/reflections/ReflectionsMetaResolver.java
crnk-meta/src/main/java/io/crnk/meta/internal/resource/ResourceMetaParitition.java

nested subtypes can now share a @JsonApiResource.resourcePath with the root resource and do not have to implement a repository of their own.

support for deeply nested inheritance without dedicated repository #323

---

crnk-client/src/main/java/io/crnk/client/internal/ClientStubBase.java
crnk-core/src/main/java/io/crnk/core/engine/dispatcher/Response.java
crnk-core/src/main/java/io/crnk/core/engine/internal/exception/ExceptionMapperRegistry.java
crnk-core/src/main/java/io/crnk/core/engine/internal/http/JsonApiRequestProcessorBase.java
crnk-core/src/main/java/io/crnk/core/engine/internal/repository/ResponseRepositoryAdapter.java
crnk-core/src/main/java/io/crnk/core/exception/ForbiddenException.java
crnk-operations/src/main/java/io/crnk/operations/client/OperationsCall.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsRequestProcessor.java
crnk-operations/src/test/java/io/crnk/operations/AbstractOperationsTest.java
crnk-operations/src/test/java/io/crnk/operations/OperationsSecurityTest.java

The OperationsModule now performs all security checks before executing any operations/accessing any repositories. Useful if updates are non-atomar and one of the non-first operations fails.

Early verification of security constraints for bulk operations

---

crnk-meta/src/main/java/io/crnk/meta/internal/resource/ResourceMetaParitition.java
crnk-meta/src/main/java/io/crnk/meta/model/MetaAttribute.java
crnk-validation/src/main/java/io/crnk/validation/internal/ConstraintViolationExceptionMapper.java
crnk-validation/src/main/java/io/crnk/validation/internal/ConstraintViolationImpl.java
crnk-validation/src/test/java/io/crnk/validation/ValidationEndToEndTest.java
crnk-validation/src/test/java/io/crnk/validation/mock/models/Project.java

Resolves #406 
In order to fix `ValidationMetaProviderTest` I had to modify `ResourceMetaPartition` and `MetaAttribute`. Not sure if that's the right approach, though.

support for renamed attributes in error-response

---

crnk-core/src/main/java/io/crnk/core/queryspec/mapper/DefaultQuerySpecUrlMapper.java
crnk-core/src/test/java/io/crnk/core/queryspec/mapper/DefaultQuerySpecUrlMapperSerializerTest.java

Disables by default support for
```
filter[person][address][city]=Zurich
filter[address][city]=Zurich
```
in favor of
```
filter[person][address.city]=Zurich
filter[address.city]=Zurich
```
to avoid by default ambiguity if relationships and resources are named equally.

Enable enforceDotSeparator by default #405

---

crnk-client/src/main/java/io/crnk/client/internal/RelationshipRepositoryStubImpl.java
crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/RelationshipsResourceGetController.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/JsonApiUrlBuilder.java
crnk-core/src/test/java/io/crnk/core/engine/internal/dispatcher/controller/resource/RelationshipsResourceGetControllerTest.java
crnk-documentation/src/docs/asciidoc/repositories.adoc
crnk-documentation/src/docs/releases/latest/info.html

self links no longer return entire Resource objects, but just the ResourceIdentifier
according to spec.

Supporting loading relationships according to spec #281

---

crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/DocumentMapper.java
crnk-core/src/test/java/io/crnk/core/engine/internal/document/mapper/DocumentMapperTest.java

When compact is true but the response data is null there is an exception due to doc.getData().isPresent() returning false but still continuing to try to access the data.
I believe the else statement is simply at the wrong level of indentation. The test added shows that the error occurs until the else block is moved.

Fix issue with compact result where data is null.

---

crnk-setup/crnk-setup-spring-boot2/build.gradle
crnk-setup/crnk-setup-spring-boot2/src/main/java/io/crnk/spring/setup/boot/metrics/CrnkSpringActuatorMetricsAutoConfiguration.java
crnk-setup/crnk-setup-spring-boot2/src/main/java/io/crnk/spring/setup/boot/metrics/CrnkWebMvcTagsProvider.java
crnk-setup/crnk-setup-spring-boot2/src/main/resources/META-INF/spring.factories
crnk-setup/crnk-setup-spring-boot2/src/test/java/io/crnk/spring/metrics/CrnkWebMvcTagsProviderTest.java

Added custom tags-provider and implementation auto-configuration to define it, which properly resolves uri for any crnk resource
Partially resolves #451

Crnk spring actuator metrics support

---

crnk-core/src/main/java/io/crnk/core/repository/decorate/WrappedOneManyRelationshipRepository.java
crnk-gen/crnk-gen-asciidoc/src/main/java/io/crnk/gen/asciidoc/capture/AsciidocCaptureModule.java
crnk-gen/crnk-gen-asciidoc/src/test/java/io/crnk/gen/asciidoc/AsciiDocCaptureTest.java

Add new decorator class for RelationshipRepository entity and redirect calss to one and many decorators.
Add some tests for check decoration correctness.
@remmeier, please see changes. I am not sure that I do right work with the problem.

#532: AsciidocCaptureModule wrong decorate ManyRelationshipRepository

---

crnk-core/src/main/java/io/crnk/core/engine/internal/utils/ClassUtils.java

Hi,
I'm using Crnk with Kotlin. I've created a User model and assign it a set of Role. The signature of Set in Kotlin is Set<out E> and Role is a Java class so not final by default. 
At runtime it gives the following signatrue Set<? extends io.crnk.security.repository.Role>.
? extends io.crnk.security.repository.Role is a WildcardType and in ClassUtils getRawType it will throw an IllegalStateException with unknown type.
This pull request add the required conditional branch for WildcardType and solve the bug.
Best,
JB

ClassUtils getRawType function should check for WildcardType

---

crnk-documentation/src/docs/asciidoc/operations.adoc
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/test/java/io/crnk/operations/OperationsDisplayOperationResponseOnSuccessTest.java
crnk-operations/src/test/java/io/crnk/operations/OperationsResumeOnErrorTest.java

Added a couple of toggles in the operations module to fix issues in #506. This greatly improves performance for entities which contain many foreign keys. Added a displayOperationResponseOnSuccess toggle which allows to only display the status to decrease the size of the response you get back. 
Also updated the documentation to reflect these changes. 
Thanks!

Operations Including All Relationships Toggle

---

crnk-gen/crnk-gen-gradle/src/main/java/io/crnk/gen/gradle/GeneratorExtension.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/OpenAPIGeneratorModule.java

Regarding #581 there was missing implementation on crnk-gen-gradle module which allows to put configuration into gradle file.
Here is the missing part

Added support for OpenAPI generation into crnk-gen-gradle.

---

crnk-core/src/main/java/io/crnk/core/engine/error/ErrorResponse.java
crnk-core/src/test/java/io/crnk/core/engine/error/ErrorResponseBuilderTest.java
crnk-core/src/test/java/io/crnk/core/exception/CrnkExceptionMapperTest.java
crnk-test/src/main/java/io/crnk/test/mock/TestExceptionMapper.java

Not sure if this is by design, so ignore this pull request if I'm in error. not sure if this was a design decision or an oversight, as the git history of the ErrorResponse method getResponse() from day one has always been returning "new JsonApiResponse().setEntity(data);" instead of "new JsonApiResponse().setErrors(data);". 
At the same time even though it has always been calling setEntity, I think this might be an oversight since the online [spec](https://jsonapi.org/format/#error-objects) currently states: "Error objects MUST be returned as an array keyed by errors in the top level of a JSON:API document."

ErrorResponse.getResponse() serializes as "entity" instead of "errors"

---

crnk-documentation/src/docs/asciidoc/operations.adoc
crnk-operations/src/main/java/io/crnk/operations/client/OperationsCall.java
crnk-operations/src/main/java/io/crnk/operations/server/OperationsModule.java
crnk-operations/src/test/java/io/crnk/operations/OperationsDeleteTest.java
crnk-operations/src/test/java/io/crnk/operations/OperationsGetTest.java

The thing preventing bulk GETs from working was that in OperationsModule the query string wasn't stripped from the path before passing it into the PathBuilder. I fixed this, and also used the existing "enrichTypeIdInformation" method so GET operations don't need to provide the operation's "value" field.
To test this using OperationsCall I added another "add" method which takes the URL path instead of the target resource. This method can be used for GET or DELETE calls which only need a path.
Fixes #662

crnk-operations bulk find-one

---

crnk-core/src/main/java/io/crnk/core/queryspec/QuerySpec.java
crnk-core/src/test/java/io/crnk/core/queryspec/QuerySpecTest.java
crnk-ui/package-lock.json

Hi @remmeier 
This PR should solve #636 
I've split relatedSpecs between resourceType and resourceClass as you proposed.
I've used a Set to return the relatedSpecs in order to remove duplicates Specs (those who are both related to a resourceType and a resourceClass).
Let me know if it is what you were looking for.
Thx
JB

QuerySpecs creation with targetResourceType or targetResource Class

---

crnk-core/src/main/java/io/crnk/core/queryspec/internal/JsonFilterSpecMapper.java
crnk-core/src/test/java/io/crnk/core/queryspec/mapper/JsonFilterSpecMapperTest.java

Fixes issue #680.
Filters nested under an AND operator are now correctly serialized as a JSON array.

Fix incorrect serialization of nested filtering with AND operator

---

crnk-gen/crnk-gen-typescript/src/main/java/io/crnk/gen/typescript/model/writer/TSWriter.java
crnk-gen/crnk-gen-typescript/src/test/java/io/crnk/gen/typescript/model/TSWriterTest.java
crnk-gen/crnk-gen-typescript/src/test/resources/expected_primitive_plain_json.ts
crnk-test/src/main/java/io/crnk/test/mock/models/PrimitiveAttributeResource.java

Add distinction between string/number, enum and everything else when transforming java map into typescript.
Created unit tests for the new conditions.
Fix for issue [708](https://github.com/crnk-project/crnk-framework/issues/708)

Fix transformation of java map to typescript

---

crnk-core/src/main/java/io/crnk/core/engine/internal/utils/PropertyUtils.java
crnk-core/src/test/java/io/crnk/core/engine/internal/utils/PropertyUtilsTest.java

Fixed issue #702 where getting a property of a bean where more than one of its parents is a collection.

Get property where attribute path contains more than one iterable

---

crnk-core/src/main/java/io/crnk/core/engine/internal/utils/UrlUtils.java
crnk-setup/crnk-setup-rs/src/main/java/io/crnk/rs/CrnkFilter.java
crnk-setup/crnk-setup-rs/src/main/java/io/crnk/rs/JaxrsRequestContext.java
crnk-setup/crnk-setup-rs/src/test/java/io/crnk/rs/CrnkFilterTest.java
crnk-setup/crnk-setup-rs/src/test/java/io/crnk/rs/JaxrsRequestContextTest.java
crnk-setup/crnk-setup-rs/src/test/java/io/crnk/rs/controller/ControllerTest.java
crnk-setup/crnk-setup-rs/src/test/java/io/crnk/rs/controller/ControllerWithPrefixTest.java

Goes with #707.
I kept all the changes inside the jax-rs-setup. Tried to add some tests too, although the CrnkFilterTest ones seem kinda bad. The biggest problem is the leading/trailing slash handling. The uriInfo.getPath() returns a leading slash on Wildfly and no leading slash on Glassfish.

JAX-RS integrations webpath prefix handling

---

crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/OASResource.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/OASUtils.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/AbstractResourceAttributes.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/AbstractSchemaGenerator.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PatchResource.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PostResourceData.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourceAttributes.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourceLinks.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourcePatchAttributes.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourcePatchRelationships.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourcePostAttributes.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourcePostRelationships.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourceRelationships.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/ResourceSchema.java
crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/TypeSchema.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/MetaResourceBaseTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/parameters/FieldsTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PatchResourceTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/PostResourceDataTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/ResourceAttributesTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/ResourcePatchRelationshipsTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/ResourcePostRelationshipsTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/ResourceRelationshipsTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/ResourceSchemaTest.java
crnk-gen/crnk-gen-openapi/src/test/java/io/crnk/gen/openapi/internal/schemas/TypeSchemaTest.java
crnk-gen/crnk-gen-openapi/src/test/resources/gold/complex.yaml
crnk-gen/crnk-gen-openapi/src/test/resources/gold/simple.yaml

* Generate OpenAPI resource types with correct letters case
* Fix schemas containing or defining resource attributes and relationships
* relationship fields separated from attributes
* only valid (containing at least one property) relationships and attributes schemas are generated
* enhanced relationship inner structures
* links (with explicitly defined self link) in separate schema
Fixes https://github.com/crnk-project/crnk-framework/issues/695

Fix OpenAPI generator type field and relationships issues

---

crnk-core/src/main/java/io/crnk/core/engine/http/HttpMethod.java

will allow custom extensions to make use of those methods

cover non-JSON:API HTTP method by constants

---

crnk-client/src/main/java/io/crnk/client/http/okhttp/OkHttpRequest.java

Listeners are not invoked as request is built before their registration.

Fix premature builder invocation in okhttp

---

README.md

This MR aims to fix the JSON API specification link on the `README.md` file.

Fixes json api link on readme file

---

crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourceUpsert.java

I was writing some tests around this in one of my projects and ran into this issue. Example of the error before the fix as it is looks like this:
```
{
"errors": [
{
"status": "400",
"title": "BAD_REQUEST",
"detail": "attribute versionBetween110And120 not available for version {}"
}
]
}
```

Fixed exception message to correctly contain the applicable application version

---

crnk-core/src/main/java/io/crnk/core/engine/internal/document/mapper/DocumentMapper.java
crnk-core/src/main/java/io/crnk/core/engine/internal/utils/UrlUtils.java
crnk-core/src/main/java/io/crnk/core/engine/query/QueryContext.java
crnk-core/src/test/java/io/crnk/core/engine/internal/document/mapper/DocumentMapperTest.java
crnk-integration-examples/spring-boot-example/src/test/java/io/crnk/example/springboot/simple/SpringBootCustomServiceUrlProviderApplicationTests.java

fix(core): made sure self links at document level use service-url-provider as base url

---

crnk-setup/crnk-setup-spring-boot2/build.gradle
crnk-setup/crnk-setup-spring-boot2/src/main/java/io/crnk/spring/setup/boot/mvc/CrnkErrorController.java
crnk-setup/crnk-setup-spring-boot2/src/test/java/io/crnk/spring/boot/BasicSpringBoot2Test.java

The `getErrorAttributes` method that the `CrnkErrorController` was calling had been deprecated in Spring Boot 2.3 and then was removed in Spring Boot 2.5 - this pull request updates the controller to use the new / non-deprecated version of the `getErrorAttributes` method.
Closes #816

Update CrnkErrorController to be compatible with Spring Boot >= 2.3.X

---

.gitignore
crnk-core/build.gradle
crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/ResourceInformationProviderBase.java
crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/information/JpaResourceInformationProviderTest.java
crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/model/TestInterfaceWithGenerics.java
crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/model/TestMappedSuperclassWithGenericsInterface.java
crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/model/TestSubclassWithSuperclassGenericsInterface.java
versions.properties

This is a PR to resolve issue: #500
We are trying to use Crnk in a project and have some issues with crnk-core when resolving self-referential type-declarations on MappedSuperclasses used in crnk-data-jpa. Crnk cannot properly resolve MappedSuperclass of type: `class Foo<T extends Bar<T>> implements Bar<T>` for the opposite resource type.
This PR contains a correction for this, with included JUnit tests.
This PR also requires an updated TypeTools library, see PR jhalterman/typetools#53 that is pending approval. (Same update of TypeTooles is referenced in crnk-project/crnk-framework#512)

Add support for nestled self-referenced generics

---

.github/workflows/build.yml
README.md
build.gradle

This pull request updates the GitHub Actions workflow to use [Eclipse Temurin](https://projects.eclipse.org/projects/adoptium.temurin), which is the successor to AdoptOpenJDK.
Additional updates include upgrading the `gradle-git-publish` plugin versions to support retrieval from Maven Central using versions compatible with Java 8.

Update GitHub Actions to use Temurin
